# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c1d532d1520f80d3a10957c2efe8dcaf31d24494e053d4f641c18314d95b2a384545d990a54d827556539c0346c46b0a8703aafe20d15c9399f81de5ecc7a1

test:
  secret_key_base: cca7ee0874aa360d4476ecfd99363dc922584d4d6ac9c91eea71da715f019adfa58f045947cb3a27fd19275f22c1387b232697f6ddc5efbb3f2e3824e1d4af2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
